server:
  port: 8082
spring:
  profiles:
    active:
      - dev
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    config:
      label: main
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 2000
        multiplier: 1.5
  main:
    allow-bean-definition-overriding: true

  application:
    name: course-instance-service
